import Link from "next/link";
import { Church, ArrowRight, FilePenLine } from "lucide-react";
import Container from "@/components/ui/Container";
export default function EntryOffers({title="Two Simple Ways to Get Started"}:{title?:string}) {
 return <section className="py-14 sm:py-20"><Container>
 <p className="text-xs font-bold uppercase tracking-[.2em] text-secondary">Professional websites don’t have to start with a huge bill.</p>
 <h2 className="mt-4 font-display text-3xl text-ink sm:text-4xl">{title}</h2>
 <p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted">Whether your church needs a new website or your existing business website simply needs better content, AJH Digital makes it affordable and simple to get started.</p>
 <div className="mt-9 grid gap-6 lg:grid-cols-[1.1fr_1fr]">
 <article className="rounded-3xl bg-ink p-7 text-background shadow-card sm:p-10"><Church className="size-9 text-accent" aria-hidden="true"/><p className="mt-5 text-sm font-semibold text-accent">Church &amp; Ministry Websites</p><h3 className="mt-3 font-display text-3xl text-background">Professional Church Websites Starting at $25/Month</h3><p className="mt-5 leading-relaxed text-background/80">Give your church or ministry a modern, mobile-friendly website without a huge upfront investment.</p><p className="mt-7 text-3xl font-semibold">Starting at $25/month</p><p className="mt-3 font-semibold">No long-term contracts. Cancel anytime.</p><p className="mt-3 text-sm text-background/80">Choose $25/month + $99 setup or $49/month with $0 setup.</p><Link className="mt-7 inline-flex items-center gap-2 rounded-full bg-cta px-6 py-3 font-semibold text-cta-foreground" href="/church-websites">Explore Church Websites <ArrowRight className="size-4"/></Link></article>
 <article className="rounded-3xl border border-border bg-surface-alt p-7 sm:p-10"><FilePenLine className="size-9 text-primary" aria-hidden="true"/><p className="mt-5 text-sm font-semibold text-secondary">Website Content Refresh</p><h3 className="mt-3 font-display text-3xl text-ink">Your Website May Not Need a Rebuild. It May Just Need Better Content.</h3><p className="mt-5 leading-relaxed text-muted">Refresh up to 5 pages of your existing website with clearer messaging, stronger calls-to-action, better readability, improved structure, and content-level SEO.</p><p className="mt-7 text-3xl font-semibold text-ink">Starting at $99</p><p className="mt-3 text-sm text-muted">This improves your website’s content. It is not a complete website redesign or custom development package.</p><Link className="mt-7 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3 font-semibold text-background" href="/content-refresh">Refresh My Website <ArrowRight className="size-4"/></Link></article>
 </div></Container></section>;
}
