import Link from "next/link";
import { Church, Store, ArrowRight, FilePenLine } from "lucide-react";
import Container from "@/components/ui/Container";
export default function EntryOffers({title="Affordable Websites for Small Businesses and Churches"}:{title?:string}) {
 return <section className="py-14 sm:py-20"><Container>
 <p className="text-xs font-bold uppercase tracking-[.2em] text-secondary">Professional websites don’t have to start with a huge bill.</p>
 <h2 className="mt-4 font-display text-3xl text-ink sm:text-4xl">{title}</h2>
 <p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted">Choose a professionally managed standard website for your business or church. Already have a website? Our Content Refresh offer can help you improve what it says.</p>
 <div className="mt-9 grid gap-6 lg:grid-cols-2">
 <article className="rounded-3xl bg-ink p-7 text-background shadow-card sm:p-10"><Church className="size-9 text-accent" aria-hidden="true"/><p className="mt-5 text-sm font-semibold text-accent">Church &amp; Ministry Websites</p><h3 className="mt-3 font-display text-3xl text-background">Professional Church & Ministry Websites Starting at $25/Month</h3><p className="mt-5 leading-relaxed text-background/80">Give your church or ministry a modern, mobile-friendly website without a huge upfront investment.</p><p className="mt-7 text-3xl font-semibold">Starting at $25/month</p><p className="mt-3 font-semibold">No long-term contracts. Cancel anytime.</p><p className="mt-3 text-sm text-background/80">Choose $25/month + $99 setup or $49/month with $0 setup.</p><Link className="mt-7 inline-flex items-center gap-2 rounded-full bg-cta px-6 py-3 font-semibold text-cta-foreground" href="/church-websites">Explore Church & Ministry Websites <ArrowRight className="size-4"/></Link></article>
 <article className="rounded-3xl bg-ink p-7 text-background shadow-card sm:p-10"><Store className="size-9 text-accent" aria-hidden="true"/><p className="mt-5 text-sm font-semibold text-accent">Small Business Websites</p><h3 className="mt-3 font-display text-3xl text-background">A Professional Business Website Starting at $49/Month</h3><p className="mt-5 leading-relaxed text-background/80">Simple websites. Professional results. Affordable monthly pricing. Hosting and ongoing website management included.</p><p className="mt-7 text-3xl font-semibold">Starting at $49/month</p><p className="mt-3 font-semibold">No long-term contracts. Cancel anytime.</p><p className="mt-3 text-sm text-background/80">Choose $49/month + $199 setup or $99/month with no setup fee.</p><p className="mt-3 text-sm text-background/80">For standard small business websites. Custom functionality, integrations, e-commerce, booking and third-party services are quoted separately.</p><Link className="mt-7 inline-flex items-center gap-2 rounded-full bg-cta px-6 py-3 font-semibold text-cta-foreground" href="/small-business-websites">Explore Small Business Websites <ArrowRight className="size-4"/></Link></article>
 <article className="rounded-3xl border border-border bg-surface-alt p-7 sm:p-10 lg:col-span-2"><FilePenLine className="size-9 text-primary" aria-hidden="true"/><p className="mt-5 text-sm font-semibold text-secondary">Website Content Refresh</p><h3 className="mt-3 font-display text-3xl text-ink">Your Website May Not Need a Rebuild. It May Just Need Better Content.</h3><p className="mt-5 leading-relaxed text-muted">Refresh up to 5 pages of your existing website with clearer messaging, stronger calls-to-action, better readability, improved structure, and content-level SEO.</p><p className="mt-7 text-3xl font-semibold text-ink">Starting at $99</p><p className="mt-3 text-sm text-muted">This improves your website’s content. It is not a complete website redesign or custom development package.</p><Link className="mt-7 inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3 font-semibold text-background" href="/content-refresh">Refresh My Website <ArrowRight className="size-4"/></Link></article>
 </div></Container></section>;
}
