import Link from "next/link";
import Container from "@/components/ui/Container";
import {withBrandMetadata} from "@/lib/social";
export const metadata=withBrandMetadata({title:"Website Content Refresh — $99 for Up to 5 Pages",description:"Improve website messaging, readability, calls-to-action and content-level SEO. $99 for up to five pages, then $55 per page up to ten total. Content only.",alternates:{canonical:"/content-refresh"}});
export default function ContentRefresh(){return <>
 <section className="bg-ink py-16 text-background sm:py-24"><Container><p className="text-sm font-bold uppercase tracking-[.18em] text-accent">Website Content Refresh</p><h1 className="mt-5 max-w-4xl font-display text-4xl leading-tight text-background sm:text-6xl">Your Website May Not Need a Rebuild. It May Just Need Better Content.</h1><p className="mt-7 text-3xl font-semibold">$99 — Up to 5 Pages</p><p className="mt-5 max-w-3xl text-lg leading-relaxed text-background/80">Make the website you already have clearer, easier to read and more useful. AJH Digital’s website content services improve existing copy so visitors understand what you offer and what to do next.</p><Link href="/pricing?service=website-content-refresh#project-details" className="mt-8 inline-flex rounded-full bg-cta px-7 py-4 font-semibold text-cta-foreground">Refresh My Website</Link></Container></section>
 <section className="py-16"><Container><div className="grid gap-10 lg:grid-cols-2"><div><h2 className="font-display text-3xl text-ink">Better content. A clearer message.</h2><ul className="mt-7 space-y-4">{["Content review","Improved messaging and existing website copy","Improved readability","Stronger calls-to-action","Better content organization","Content-level SEO improvements where applicable","Basic content recommendations"].map(x=><li key={x} className="rounded-xl border border-border bg-surface p-4">✓ {x}</li>)}</ul></div><div className="rounded-3xl bg-surface-alt p-8"><h2 className="text-2xl font-semibold">Additional Pages</h2><dl className="mt-6 space-y-5"><div><dt>Up to 5 agreed pages</dt><dd className="text-3xl font-semibold">$99</dd></div><div><dt>After the first 5 pages</dt><dd className="text-3xl font-semibold">$55 per additional page</dd></div><div><dt>Maximum standard Content Refresh</dt><dd className="text-xl font-semibold">10 pages — $374 total</dd></div></dl><p className="mt-6 leading-relaxed">Add up to five additional pages under this package. More than ten pages receive a custom quote. Payment is due before work begins.</p><p className="mt-5 leading-relaxed">This is a one-time service. There is no ongoing monthly commitment unless you separately purchase another AJH Digital service.</p></div></div></Container></section>
 <section className="border-y border-border bg-surface-alt py-14"><Container><h2 className="font-display text-3xl text-ink">Focused on your website’s content</h2><p className="mt-5 max-w-3xl leading-relaxed">This is not a complete website redesign or custom development package. Extensive design changes, new functionality, major integrations, structural changes, unlimited revisions and work outside the agreed pages require a separate quote and your approval.</p><p className="mt-5 max-w-3xl leading-relaxed">Provide your existing website, the pages to refresh, necessary business information and website access when needed. We’ll confirm the scope and ask for timely feedback and approval.</p><p className="mt-5 max-w-3xl leading-relaxed">Content-level SEO can improve your website’s foundations, but AJH Digital does not guarantee search rankings, traffic, leads, sales, revenue or specific SEO outcomes.</p><Link href="/pricing?service=website-content-refresh#project-details" className="mt-7 inline-flex rounded-full bg-cta px-6 py-3 font-semibold text-cta-foreground">Refresh My Website</Link></Container></section>
 </>;}
