import Link from "next/link";
import Container from "@/components/ui/Container";
import { withBrandMetadata } from "@/lib/social";
import { churchPlans } from "@/lib/entry-offers";
export const metadata=withBrandMetadata({title:"Affordable Church & Ministry Websites",description:"Church website design starting at $25/month + $99 setup or $49/month with $0 setup. Hosting, maintenance and routine content updates. No long-term contracts.",alternates:{canonical:"/church-websites"}});
const included=["Professionally built church/ministry website","Mobile-friendly responsive design","AJH Digital church website template/design system","Hosting","Routine maintenance and technical upkeep","Reasonable routine content updates","Core church website pages/features","No long-term contract — cancel anytime"];
const faqs=[
 ["Is there a contract?","Church Website plans are month-to-month with no long-term contract commitment. A service agreement records your selected plan and scope."],
 ["Can we cancel anytime?","Yes. You can cancel the recurring service at any time. Cancellation stops future renewals."],
 ["What’s the difference between the $25 and $49 plans?","The $25/month Essential plan requires a $99 one-time setup fee. The $49/month Simple Start plan has no setup fee. Both currently include the same core church website service."],
 ["Why would we choose the $49 plan?","It allows your church to launch without paying an upfront setup fee."],
 ["Can you use our existing domain?","Generally yes, assuming your church owns or controls the domain and provides the necessary access."],
 ["Can you connect Planning Center?","Standard links and supported connections can generally be included. Advanced/custom integrations may require additional charges."],
 ["Can you update the website for us?","Yes. Reasonable routine content updates are included, such as service times, existing text, staff details, links, basic events and provided images. Major redesigns, new functionality, custom development, or unusually extensive changes may require a separate quote."],
 ["Do you build larger custom church websites?","Yes. Churches needing functionality beyond the streamlined Church Website program can request a custom project quote."],
 ["What happens if we need something outside the standard plan?","AJH Digital will review your request and communicate any additional cost for your approval before performing work outside the included service scope."]
];
const button="inline-flex justify-center rounded-full bg-cta px-6 py-3 font-semibold text-cta-foreground hover:bg-cta-hover";
export default function ChurchWebsites(){return <>
 <section className="bg-ink py-16 text-background sm:py-24"><Container><p className="text-sm font-bold uppercase tracking-[.18em] text-accent">Church &amp; Ministry Websites</p><h1 className="mt-5 max-w-4xl font-display text-4xl leading-tight text-background sm:text-6xl">A Better Church Website Without the Big Upfront Cost</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-background/80">AJH Digital helps churches, church plants, ministries, and Christian organizations launch professional, modern websites without spending thousands of dollars upfront.</p><p className="mt-7 text-3xl font-semibold">Starting at $25/month</p><p className="mt-3">No long-term contracts. Cancel anytime.</p><a href="#plans" className={button+" mt-7"}>Start My Church Website</a></Container></section>
 <section id="plans" className="scroll-mt-28 py-16 sm:py-20"><Container><h2 className="font-display text-3xl text-ink sm:text-4xl">One core service. Choose your payment plan.</h2><div className="mt-9 grid gap-6 md:grid-cols-2">{churchPlans.map(p=><article key={p.id} className="flex flex-col rounded-3xl border border-border bg-surface p-7 shadow-card sm:p-9"><p className="text-sm font-semibold text-secondary">{p.badge}</p><h3 className="mt-4 text-2xl font-semibold">{p.name}</h3><p className="mt-5 text-5xl font-semibold text-ink">${p.monthly}<span className="text-lg font-normal">/month</span></p><p className="mt-3 text-xl font-semibold">${p.setup} {p.setup ? "one-time setup" : "setup"}</p><p className="mt-3 text-muted">{p.setup ? "$99 setup + $25/month. Setup is charged before setup/build work begins." : "Start for $0 upfront. $0 setup + $49/month."}</p><ul className="my-7 space-y-3 text-sm">{included.map(x=><li key={x} className="flex gap-2"><span aria-hidden="true" className="text-primary">✓</span>{x}</li>)}</ul><Link className={button+" mt-auto"} href={`/pricing?service=${p.id}#project-details`}>Choose {p.name}</Link></article>)}</div>
 <div className="mt-9 rounded-2xl bg-surface-alt p-7"><h2 className="text-2xl font-semibold">Same Great Website. Two Ways to Get Started.</h2><p className="mt-4">Want the lowest monthly payment? Choose $25/month and pay a $99 one-time setup fee.</p><p className="mt-3">Want to start without an upfront setup fee? Choose $49/month with $0 setup.</p><p className="mt-4">Both plans include the same core church website service. Both are month-to-month, with no long-term contract. You can cancel the recurring service at any time. Cancellation stops future renewals.</p></div></Container></section>
 <section className="bg-surface-alt py-16"><Container><h2 className="font-display text-3xl text-ink">Built around the life of your church</h2><p className="mt-5 max-w-3xl leading-relaxed text-muted">Our affordable church websites help people find your service times, plan a visit and connect with your ministry. Church website management keeps essential information current, including for small churches without a dedicated web team.</p><ul className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Home","I’m New / Plan Your Visit","About & Beliefs","Leadership","Ministries","Kids & Students","Events","Sermons / Messages","Giving links","Contact","Baptism / Signup links","Planning Center links","Social media links","Service times","Location information"].map(x=><li key={x} className="rounded-xl border border-border bg-background p-4">{x}</li>)}</ul><p className="mt-7 leading-relaxed">Exact pages and functionality depend on your church’s needs and agreed project scope. Advanced integrations, premium third-party services or plugins, custom databases, major custom development, significant custom functionality and extensive redesigns may require additional charges. We will communicate those charges and get your approval before performing additional work.</p></Container></section>
 <section className="py-16"><Container><div className="rounded-3xl bg-ink p-8 text-background sm:p-12"><p className="text-sm font-semibold text-accent">Jubilee City Church</p><h2 className="mt-4 font-display text-3xl text-background">See a Church Website in Action</h2><p className="mt-5 max-w-3xl leading-relaxed text-background/80">Jubilee City Church is an example of the clean, modern, mobile-friendly church website experience AJH Digital can create. Your website can be customized to your church’s branding, content, ministries and needs.</p><a className={button+" mt-7"} href="https://jubileecity.church" target="_blank" rel="noopener noreferrer">Visit Jubilee City Church ↗</a></div></Container></section>
 <section className="pb-16"><Container><h2 className="font-display text-3xl text-ink">Questions about church website services</h2><div className="mt-8 divide-y divide-border border-y border-border">{faqs.map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer font-semibold text-ink">{q}</summary><p className="mt-3 max-w-3xl leading-relaxed text-muted">{a}</p></details>)}</div><div className="mt-9 flex flex-wrap gap-4"><a className={button} href="#plans">Start My Church Website</a><Link className="rounded-full border border-border px-6 py-3 font-semibold" href="/pricing?service=church-websites#project-details">Request a custom church website</Link></div></Container></section>
 </>;}
