import 'server-only';
import {Resend} from 'resend';
import {siteConfig} from './site-config';
export type DocumentEmail={id:string;event:'invoice_sent'|'invoice_paid'|'agreement_sent'|'agreement_signed'|'agreement_completed'|'request_reply'|'delivery_test'|'client_welcome';recipient:'client'|'owner';email:string;client:string;recordId:string;invoiceNumber:string|null;balance:number|null;dueDate:string|null};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function documentEmail(n:DocumentEmail){
 if(n.event==='client_welcome') {
  const title='Welcome to AJH Digital';
  const detail='We look forward to working with you. Your client portal is where you can review shared projects, invoices and agreements, request updates, and exchange project files. If you already have portal access, sign in with your existing account. If you received a separate invitation, follow that invitation to set up access. Otherwise, contact us to arrange your portal setup; this welcome email does not activate an account.';
  const url='https://client.ajhdigital.com/portal';
  return {subject:title,text:`${title}\n${n.client}\n\n${detail}\n\nClient Portal: ${url}\nQuestions? ${siteConfig.email}\n\nAJH Digital`,html:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#123047;padding:28px"><h1>${title}</h1><p>${escape(n.client)}</p><p>${escape(detail)}</p><p><a href="${url}">Open Client Portal</a></p><p>Questions? <a href="mailto:${siteConfig.email}">${siteConfig.email}</a></p></div>`};
 }
const invoice=n.event.startsWith('invoice');const title={invoice_sent:'Your invoice is ready',invoice_paid:'Payment recorded',agreement_sent:'Your agreement is ready to review and sign',agreement_signed:n.recipient==='owner'?'Client signed — your countersignature is needed':'Your signature is saved — awaiting AJH Digital',agreement_completed:'Fully signed agreement is ready',request_reply:'AJH Digital replied to your request',delivery_test:'TEST ONLY — Email notification verification'}[n.event];const path=`${invoice?'invoices':'agreements'}/${n.recordId}`;const url=n.event==='request_reply'?`https://client.ajhdigital.com/portal#request-${n.recordId}`:n.event==='delivery_test'?`${siteConfig.crmUrl}/notifications`:n.recipient==='owner'?`${siteConfig.crmUrl}/${path}`:`https://client.ajhdigital.com/portal/${path}`;const detail=n.event==='request_reply'?'You have a new reply from AJH Digital. Sign in to read it in your request history. Reply there if you need anything else.':n.event==='delivery_test'?'This is a clearly labeled AJH Digital delivery test. No invoice, payment, signature or client email was created.':invoice?`${n.invoiceNumber??'Invoice'}${n.event==='invoice_sent'?` — remaining balance ${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n.balance))}; due ${n.dueDate}.`:'. A payment has been recorded; view the invoice for payment history.'}`:n.event==='agreement_sent'?'Please sign in to your client portal to review the complete agreement and sign if you agree.':n.event==='agreement_signed'?(n.recipient==='owner'?'The client has signed. Open the agreement to review and add your AJH Digital countersignature.':'Your signature is saved. AJH Digital will countersign, then both parties can access the fully signed copy. No action is needed from you now.'):'Both parties have signed. Your fully signed copy is saved and available to print or save as PDF.';return {subject:`AJH Digital — ${title}${n.invoiceNumber?' · '+n.invoiceNumber:''}`,text:`${title}\n${n.client}\n\n${detail}\n\nOpen securely: ${url}\n\nAJH Digital`,html:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#123047;padding:28px;border-top:6px solid #a95e45"><p>AJH Digital</p><h1>${escape(title)}</h1><p>${escape(n.client)}</p><p>${escape(detail)}</p><p><a href="${escape(url)}" style="display:inline-block;padding:14px 20px;background:#123047;color:white;border-radius:8px">${n.event==='request_reply'?'Read reply':invoice?'View invoice':'View agreement'}</a></p><p style="font-size:12px">Sign in with your existing portal account. This email does not contain the document or a public access link.</p></div>`};}
export async function deliverDocumentEmail(n:DocumentEmail){const key=process.env.RESEND_API_KEY,from=process.env.CONTACT_FROM_EMAIL;if(!key||!from)throw new Error('Email configuration is unavailable.');const resend=new Resend(key);const result=await resend.emails.send({from,to:n.email,replyTo:siteConfig.email,...documentEmail(n)},{idempotencyKey:`crm-document-${n.id}`});if(result.error||!result.data?.id)throw new Error('Email provider did not accept the message.');return result.data.id;}
