export const websiteLevels=[
 {id:'standard',name:'Standard Small-Business Website',setup:'$999+',monthly:'$199+',setupMin:999,monthlyMin:199,description:'A professional informational or marketing website for small businesses, churches/nonprofits, consultants, REALTORS® and service organizations.',examples:['Responsive Home, About, Services and Contact pages','Contact forms, mobile optimization and basic technical/on-page SEO','Hosting, management and reasonable routine content updates under your plan']},
 {id:'larger',name:'Larger / Custom Business Website',setup:'$1,499–$2,499+',monthly:'$199–$299+',setupMin:1499,monthlyMin:199,description:'For greater content, design or management needs. Overall scope determines the category—not a rigid page count.',examples:['More pages, specialized landing pages, locations or service areas','Staff directories, blogs, resource libraries and advanced content organization','Content migration, custom design, advanced forms and workflows']},
 {id:'integration',name:'Brokerage / IDX / Integration Website',setup:'$1,999–$3,500+',monthly:'$249–$399+',setupMin:1999,monthlyMin:249,description:'For brokerages and websites needing substantial third-party integrations.',examples:['IDX/MLS property search and agent directories','CRM integrations, APIs and advanced lead capture','IDX, MLS, API, software, licensing and vendor fees may be additional and change independently']},
 {id:'complex',name:'Complex / Custom Development',setup:'Custom quote',monthly:'Custom quote',setupMin:0,monthlyMin:0,description:'For application-like projects requiring substantial custom development. One custom feature alone does not automatically put a whole website here.',examples:['Client/member portals, dashboards and custom applications','Accounts, authentication, complex databases and custom business workflows','Advanced automation or highly specialized integrations']}
] as const;
export type WebsiteCategory=typeof websiteLevels[number]['id'];
export const websiteFeatures=[['blog','Blog or resource section'],['directory','Staff, team or agent profiles'],['locations','Multiple locations or service-area pages'],['idx','IDX / MLS property search'],['integrations','Third-party integrations'],['accounts','User accounts / login'],['portal','Client or member portal'],['database','Custom database or application'],['workflows','Custom forms or workflows'],['migration','Existing content migration'],['management','Ongoing website management'],['seo','Interest in separate ongoing content-level SEO ($249/month)']] as const;
export type WebsiteScope={category:WebsiteCategory|'unsure';buildType:string;contentSize:string;features:string[];integrationDetails:string;idxDetails:string;accountDetails:string;workflowDetails:string};
export const blankWebsiteScope:WebsiteScope={category:'unsure',buildType:'',contentSize:'',features:[],integrationDetails:'',idxDetails:'',accountDetails:'',workflowDetails:''};
export function normalizeWebsiteScope(value:unknown):WebsiteScope{const v=value&&typeof value==='object'?value as Record<string,unknown>:{};const str=(k:string)=>typeof v[k]==='string'?(v[k] as string).trim().slice(0,3000):'';return {category:websiteLevels.some(l=>l.id===v.category)?v.category as WebsiteCategory:'unsure',buildType:str('buildType'),contentSize:str('contentSize'),features:Array.isArray(v.features)?[...new Set(v.features.filter((f):f is string=>typeof f==='string'&&websiteFeatures.some(([id])=>id===f)))]:[],integrationDetails:str('integrationDetails'),idxDetails:str('idxDetails'),accountDetails:str('accountDetails'),workflowDetails:str('workflowDetails')};}
export function suggestWebsiteCategory(scope:WebsiteScope):{category:WebsiteCategory;reason:string}{const f=new Set(scope.features);if(f.has('database')&&(f.has('portal')||f.has('accounts')))return {category:'complex',reason:'Accounts or a portal combined with a custom database suggest application-like scope.'};if(f.has('idx')||f.has('integrations'))return {category:'integration',reason:'IDX/MLS or external integrations need a closer integration review; simple integrations may fit a lower category.'};if(['blog','directory','locations','workflows','migration','accounts','portal'].some(k=>f.has(k))||scope.contentSize==='Extensive / content-heavy')return {category:'larger',reason:'Additional content, organization or workflows suggest a larger scope; review complexity before quoting.'};return {category:'standard',reason:'The supplied requirements currently resemble an informational marketing website. Confirm the full scope.'};}
export function websitePricing(scope:WebsiteScope){const suggestion=suggestWebsiteCategory(scope);return {suggestion,level:websiteLevels.find(l=>l.id===(scope.category==='unsure'?suggestion.category:scope.category))!};}
